name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: sudo apt install cmake libsdl2-dev libsdl2-ttf-dev
    - name: cmake setup
      run: mkdir build
           cd build
           cmake ..
    - name: make
      run: make
